# Constants for appknox-python

DEFAULT_APPKNOX_URL = "api.appknox.com"
DEFAULT_LOG_LEVEL = 10
DEFAULT_SECURE_CONNECTION = True

DEFAULT_LIMIT = 10
DEFAULT_OFFSET = 0

DEFAULT_REPORT_FORMAT = 'json'
DEFAULT_REPORT_LANGUAGE = 'en'

DEFAULT_VULNERABILITY_LANGUAGE = 'en'
