# (c) 2015-2017, XYSec Labs

DEFAULT_API_HOST = 'https://api.appknox.com'

DEFAULT_LIMIT = 10
DEFAULT_OFFSET = 0

DEFAULT_REPORT_FORMAT = 'json'
DEFAULT_REPORT_LANGUAGE = 'en'

DEFAULT_VULNERABILITY_LANGUAGE = 'en'
